# Generated by Django 5.0.3 on 2024-03-22 19:01

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_student_subjects_and_more'),
        ('subject_app', '0002_alter_subject_professor_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='subjects', to='student_app.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(unique=True, validators=[subject_app.validators.validate_professor_name]),
        ),
    ]
