# Generated by Django 5.0.3 on 2024-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_alter_student_subjects'),
        ('subject_app', '0004_remove_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='students', to='student_app.student'),
        ),
    ]
