# Generated by Django 5.0.3 on 2024-03-22 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_student_subjects_and_more'),
        ('subject_app', '0004_remove_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='subject_app.subject', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
